#! /usr/bin/env bash
echo "Put object in s3 bucket"
#check for bucket name
if [ -z "$1"]; then
    echo "Please provide a bucket name"
    exit 1
fi 

# check for file name
if [ -z "$2"]; then
    echo "Please provide a file name"
    exit 1
fi


BUCKET_NAME=$1
FILE_NAME=$2
OBJECT_KEY=$(basename "$FILE_NAME")

aws s3api put-object --bucket $BUCKET_NAME --body $FILE_NAME --key $OBJECT_KEY


